import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsOptional,
  IsString,
  IsBoolean,
  IsNumber,
  MaxLength,
  Min,
  IsArray,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { CreateBomLineDto } from './create-bom-line.dto';

export class CreateBomRecipeDto {
  @ApiProperty({
    description: 'The product ID this recipe belongs to',
    example: '1',
  })
  @IsString({ message: 'productId must be a string representation of ID' })
  @IsNotEmpty({ message: 'productId is required' })
  productId!: string;

  @ApiPropertyOptional({
    description: 'Version of the recipe',
    example: 'v1',
    maxLength: 30,
    default: 'v1',
  })
  @IsString({ message: 'version must be a string' })
  @MaxLength(30, { message: 'version cannot exceed 30 characters' })
  @IsOptional()
  version?: string;

  @ApiPropertyOptional({
    description: 'Output quantity of the product generated by this recipe',
    example: 1.0,
    default: 1.0,
  })
  @IsNumber({}, { message: 'outputQty must be a number' })
  @Min(0.0001, { message: 'outputQty must be greater than 0' })
  @IsOptional()
  outputQty?: number;

  @ApiPropertyOptional({
    description: 'Wastage percentage for the entire recipe (e.g. 2.5 for 2.5%)',
    example: 2.5,
    default: 0.0,
  })
  @IsNumber({}, { message: 'wastagePct must be a number' })
  @Min(0, { message: 'wastagePct cannot be negative' })
  @IsOptional()
  wastagePct?: number;

  @ApiPropertyOptional({
    description: 'Labor cost for this recipe',
    example: 15.0,
    default: 0.0,
  })
  @IsNumber({}, { message: 'laborCost must be a number' })
  @Min(0, { message: 'laborCost cannot be negative' })
  @IsOptional()
  laborCost?: number;

  @ApiPropertyOptional({
    description: 'Overhead cost for this recipe',
    example: 10.0,
    default: 0.0,
  })
  @IsNumber({}, { message: 'overheadCost must be a number' })
  @Min(0, { message: 'overheadCost cannot be negative' })
  @IsOptional()
  overheadCost?: number;

  @ApiPropertyOptional({
    description: 'Whether the recipe is active',
    default: true,
  })
  @IsBoolean({ message: 'isActive must be a boolean' })
  @IsOptional()
  isActive?: boolean;

  @ApiPropertyOptional({
    description: 'The BOM lines for this recipe',
    type: [CreateBomLineDto],
  })
  @IsArray({ message: 'bomLines must be an array' })
  @ValidateNested({ each: true })
  @Type(() => CreateBomLineDto)
  @IsOptional()
  bomLines?: CreateBomLineDto[];
}
