import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma.service';
import * as XLSX from 'xlsx';
import {
  getAllDefinitions,
  getDefinition,
  type ImportDefinition,
} from '../imports/import-definitions';
import {
  CLIENT_WORKBOOK_SHEETS,
  getSheetByModule,
  type SheetDef,
} from './client-workbook-schema';

@Injectable()
export class TemplateGeneratorService {
  constructor(private readonly prisma: PrismaService) {}

  /* ─── Full Client Workbook Template ────────────────────────────────── */

  async generateFullWorkbook(companyId?: bigint): Promise<Buffer> {
    const wb = XLSX.utils.book_new();

    const startHereWs = this.buildStartHereSheet();
    XLSX.utils.book_append_sheet(wb, startHereWs, 'START HERE');

    for (const sheet of CLIENT_WORKBOOK_SHEETS) {
      const ws = this.generateSheetWorksheet(sheet, true);
      XLSX.utils.book_append_sheet(wb, ws, sheet.sheetName);
    }

    if (companyId) {
      const refData = await this.fetchReferenceData(companyId);
      const refWs = this.buildReferenceListsSheet(refData);
      XLSX.utils.book_append_sheet(wb, refWs, 'Reference Lists');
    } else {
      const refWs = this.buildReferenceListsSheetEmpty();
      XLSX.utils.book_append_sheet(wb, refWs, 'Reference Lists');
    }

    return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
  }

  private buildStartHereSheet(): XLSX.WorkSheet {
    const rows: string[][] = [
      ['Start Here — Harvest Client Workbook Template'],
      [],
      ['Welcome to the Harvest ERP Client Workbook Template.'],
      [''],
      ['HOW TO USE THIS WORKBOOK:'],
      [
        '1. Fill each data sheet with your information. Each column is labeled with the expected data.',
      ],
      [
        '2. Required columns are marked with *. Optional columns can be left blank.',
      ],
      [
        '3. Reference data (Accounts, Sites, Cost Centers, Products, etc.) must be imported first.',
      ],
      [
        '4. Transaction data (Budget, Forecast, Actuals) can be imported after master data is loaded.',
      ],
      [
        '5. Sheets labeled as "Reference" contain lookup data for dropdowns — do not modify these directly.',
      ],
      [''],
      ['SHEETS OVERVIEW:'],
      [
        '  • Data Sheets (importable): Companies, Sites, Units, Accounts, Cost Centers,',
      ],
      [
        '    Product Categories, Customers, Suppliers, Materials, Products, BOM Recipes,',
      ],
      [
        '    Budget, Forecast, Actuals, Material Prices, Production Planning, Exchange Rates, KPI Targets',
      ],
      ['  • Reference Sheets (not imported): Reference Lists'],
      ['  • Instruction Sheets (not imported): START HERE'],
      [''],
      ['IMPORT ORDER (required):'],
      [
        '1. Companies → Sites → Units → Accounts → Cost Centers → Product Categories',
      ],
      ['2. Customers → Suppliers → Materials → Products'],
      ['3. BOM Recipes → Budget → Forecast → Actuals'],
      [
        '4. Material Prices → Production Planning → Exchange Rates → KPI Targets',
      ],
      [''],
      ['ROUND-TRIP SAFETY:'],
      [
        'This template was generated by the system. You can fill in data, save, and re-upload it.',
      ],
      [
        'The system will automatically skip this sheet and all Reference sheets during import.',
      ],
      ['Only the data sheets will be processed.'],
    ];
    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = [{ wch: 90 }];
    return ws;
  }

  private buildReferenceListsSheet(
    ref: Awaited<ReturnType<TemplateGeneratorService['fetchReferenceData']>>,
  ): XLSX.WorkSheet {
    const rows: string[][] = [
      ['Reference Lists — Master Data Lookup Values'],
      [],
      [
        'This sheet summarizes all master data available in the system for reference.',
      ],
      [
        'It is not imported. It exists only to help you fill in the correct codes and names.',
      ],
      [],
    ];

    rows.push(['=== ACCOUNTS ===', '', '']);
    rows.push(['Code', 'Name', '']);
    for (const a of ref.accounts) {
      rows.push([a.code, a.name, '']);
    }
    if (ref.accounts.length === 0)
      rows.push(['(No accounts loaded yet)', '', '']);
    rows.push([]);

    rows.push(['=== SITES ===', '']);
    rows.push(['Name', '']);
    for (const s of ref.sites) {
      rows.push([s.name, '']);
    }
    if (ref.sites.length === 0) rows.push(['(No sites loaded yet)', '']);
    rows.push([]);

    rows.push(['=== COST CENTERS ===', '', '']);
    rows.push(['Code', 'Name', '']);
    for (const cc of ref.costCenters) {
      rows.push([cc.code ?? '', cc.name, '']);
    }
    if (ref.costCenters.length === 0)
      rows.push(['(No cost centers loaded yet)', '', '']);
    rows.push([]);

    rows.push(['=== PRODUCTS ===', '', '']);
    rows.push(['SKU', 'Product Name', '']);
    for (const p of ref.products) {
      rows.push([p.sku, p.name, '']);
    }
    if (ref.products.length === 0)
      rows.push(['(No products loaded yet)', '', '']);
    rows.push([]);

    rows.push(['=== MATERIALS ===', '', '']);
    rows.push(['Code', 'Name', '']);
    for (const m of ref.materials) {
      rows.push([m.code, m.name, '']);
    }
    if (ref.materials.length === 0)
      rows.push(['(No materials loaded yet)', '', '']);
    rows.push([]);

    rows.push(['=== CUSTOMERS ===', '', '']);
    rows.push(['Code', 'Name', '']);
    for (const c of ref.customers) {
      rows.push([c.code, c.name, '']);
    }
    if (ref.customers.length === 0)
      rows.push(['(No customers loaded yet)', '', '']);
    rows.push([]);

    rows.push(['=== BUDGET CYCLES ===', '', '', '']);
    rows.push(['Budget Cycle', 'Fiscal Year', 'Status', '']);
    for (const bc of ref.budgetCycles) {
      rows.push([bc.name, String(bc.fiscalYear), bc.status ?? 'draft', '']);
    }
    if (ref.budgetCycles.length === 0)
      rows.push(['(No budget cycles loaded yet)', '', '', '']);

    const ws = XLSX.utils.aoa_to_sheet(rows);
    ws['!cols'] = [{ wch: 25 }, { wch: 40 }, { wch: 14 }, { wch: 14 }];
    return ws;
  }

  private buildReferenceListsSheetEmpty(): XLSX.WorkSheet {
    const rows: string[][] = [
      ['Reference Lists — Master Data Lookup Values'],
      [],
      ['This sheet summarizes all available master data.'],
      [
        'Since no company context was available, this reference sheet is empty.',
      ],
      [
        'After you import master data, download this template again to see populated reference values.',
      ],
      [],
      ['=== ACCOUNTS ===', '', ''],
      ['Code', 'Name', ''],
      ['(No accounts — empty reference list)', '', ''],
      [],
      ['=== SITES ===', ''],
      ['Name', ''],
      ['(No sites — empty reference list)', ''],
      [],
      ['=== COST CENTERS ===', '', ''],
      ['Code', 'Name', ''],
      ['(No cost centers — empty reference list)', '', ''],
      [],
      ['=== PRODUCTS ===', '', ''],
      ['SKU', 'Product Name', ''],
      ['(No products — empty reference list)', '', ''],
      [],
      ['=== MATERIALS ===', '', ''],
      ['Code', 'Name', ''],
      ['(No materials — empty reference list)', '', ''],
      [],
      ['=== CUSTOMERS ===', '', ''],
      ['Code', 'Name', ''],
      ['(No customers — empty reference list)', '', ''],
      [],
    ];
    return XLSX.utils.aoa_to_sheet(rows);
  }

  /* ─── Per-Module Template ──────────────────────────────────────────── */

  async generateModuleTemplate(
    moduleKey: string,
    companyId?: bigint,
  ): Promise<Buffer> {
    const sheet = getSheetByModule(moduleKey);
    if (!sheet) {
      throw new Error(`Unknown module: ${moduleKey}`);
    }

    const def = getDefinition(moduleKey) ?? getDefinition(moduleKey);
    const wb = XLSX.utils.book_new();
    const dataWs = this.generateSheetWorksheet(sheet, true);
    XLSX.utils.book_append_sheet(wb, dataWs, sheet.sheetName);

    if (companyId) {
      const refData = await this.fetchReferenceData(companyId);
      const refWs = this.buildReferenceListsSheet(refData);
      XLSX.utils.book_append_sheet(wb, refWs, 'Reference Lists');
    }

    let dataValidation: Record<string, XLSX.CellAddress[]> = {};

    if (def) {
      const refData = companyId ? await this.fetchReferenceData(companyId) : null;
      dataValidation = this.buildDataValidation(sheet, def, refData);
    }

    return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
  }

  private generateSheetWorksheet(
    sheet: SheetDef,
    includeExamples = false,
  ): XLSX.WorkSheet {
    const headers = [...sheet.columns.map((c) => c.display)];
    const rows: string[][] = [headers];

    if (includeExamples) {
      const exampleRows = this.buildExampleRows(sheet.module);
      for (const exRow of exampleRows) {
        rows.push([...exRow, 'TRUE']);
      }
      headers.push('Example');
    }

    const ws = XLSX.utils.aoa_to_sheet(rows);

    ws['!cols'] = sheet.columns.map((c) => ({
      wch: Math.max(c.display.length + 4, 18),
    }));

    return ws;
  }

  private buildExampleRows(moduleKey: string): string[][] {
    const def = getDefinition(moduleKey);
    if (def && def.sampleRows.length > 0) {
      return def.sampleRows;
    }
    return [];
  }

  private buildDataValidation(
    sheet: SheetDef,
    def: ImportDefinition,
    refData: Awaited<ReturnType<TemplateGeneratorService['fetchReferenceData']>> | null,
  ): Record<string, XLSX.CellAddress[]> {
    return {};
  }

  /* ─── Fetch Reference Data ────────────────────────────────────────── */

  private async fetchReferenceData(companyId: bigint) {
    const [accounts, sites, costCenters, products, materials, customers, budgetCycles] =
      await Promise.all([
        this.prisma.account.findMany({
          where: { companyId },
          select: { code: true, name: true },
          take: 500,
        }),
        this.prisma.site.findMany({
          where: { companyId },
          select: { name: true },
          take: 500,
        }),
        this.prisma.costCenter.findMany({
          where: { companyId },
          select: { code: true, name: true },
          take: 500,
        }),
        this.prisma.product.findMany({
          where: { companyId, isActive: true },
          select: { sku: true, name: true },
          take: 500,
        }),
        this.prisma.material.findMany({
          where: { companyId, isActive: true },
          select: { code: true, name: true },
          take: 500,
        }),
        this.prisma.customer.findMany({
          where: { companyId, isActive: true },
          select: { code: true, name: true },
          take: 500,
        }),
        this.prisma.budgetCycle.findMany({
          where: { companyId },
          select: { name: true, fiscalYear: true, status: true },
          take: 100,
        }),
      ]);

    return {
      accounts,
      sites,
      costCenters,
      products,
      materials,
      customers,
      budgetCycles,
    };
  }

  /* ─── Utility: Get module list for dropdowns ───────────────────────── */

  getModuleList(): Array<{
    key: string;
    sheetName: string;
    description: string;
    columnCount: number;
  }> {
    return CLIENT_WORKBOOK_SHEETS.map((s) => ({
      key: s.module,
      sheetName: s.sheetName,
      description: s.description,
      columnCount: s.columns.length,
    }));
  }

  /* ─── Utility: Get CSV template (backward compat) ──────────────────── */

  generateModuleCSV(moduleKey: string): string {
    const sheet = getSheetByModule(moduleKey);
    if (!sheet) {
      throw new Error(`Unknown module: ${moduleKey}`);
    }

    const headers = sheet.columns.map((c) => c.display);
    return headers.join(',');
  }
}
