export const ErrorCodes = {
  // Oracle Integration
  ORACLE_TABLE_NOT_FOUND: 'ORACLE_TABLE_NOT_FOUND',
  ORACLE_INVALID_COLUMN: 'ORACLE_INVALID_COLUMN',
  ORACLE_INVALID_CREDENTIALS: 'ORACLE_INVALID_CREDENTIALS',
  ORACLE_CONNECTION_FAILED: 'ORACLE_CONNECTION_FAILED',
  ORACLE_CLIENT_NOT_CONFIGURED: 'ORACLE_CLIENT_NOT_CONFIGURED',
  ORACLE_UNKNOWN: 'ORACLE_UNKNOWN',

  // Mapping
  MAPPING_VALIDATION_FAILED: 'MAPPING_VALIDATION_FAILED',
  MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',

  // Sync
  SYNC_FAILED: 'SYNC_FAILED',
  SYNC_NO_ROWS: 'SYNC_NO_ROWS',

  // Preview
  PREVIEW_FAILED: 'PREVIEW_FAILED',
  PREVIEW_INVALID_TABLE: 'PREVIEW_INVALID_TABLE',
  PREVIEW_INVALID_COLUMN: 'PREVIEW_INVALID_COLUMN',

  // Connection
  CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
  CONNECTION_TEST_FAILED: 'CONNECTION_TEST_FAILED',

  // AI Scenario
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_INVALID_RESPONSE: 'AI_INVALID_RESPONSE',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_PROVIDER_OVERLOADED: 'AI_PROVIDER_OVERLOADED',

  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TENANT_REQUIRED: 'AUTH_TENANT_REQUIRED',
  AUTH_TENANT_INVALID: 'AUTH_TENANT_INVALID',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
